### PR TITLE
Add THREADS env var to control number of threads

### PR DESCRIPTION
**Pull request by rlanyi**
Added a THREADS env var because the default thread count (cpu cores / 2) seems to be contraproductive on one of my servers. With 48 total cores and running `rrd-extractstats.pl` on 24 of them the process runs twice as longer than with 8 cores only.

I'm not sure of the reason yet and I use 8 cores on this server after some experiments.

Also with too many busy cores server load was too high. I'm not sure if it is related but in this case I also got some errors from `asstatsd.pl` like the one below.

```
Error updating RRD file /data/as-stats/rrd/f4/60148.rrd: could not lock RRD
```

Usage example with the env var:
```
$ THREADS=8 /root/AS-Stats/bin/rrd-extractstats.pl /data/as-stats/rrd /data/as-stats/conf/knownlinks /data/as-stats/asstats_day.txt
```

### CODE REVIEW

**Comment by JackSlateur** [comment]
@rlanyi Would you, instead of that variable, set up a max core count ?

number of thread = min(number of cpu / 2, 8)

**Comment by rlanyi** [comment]
I'm not sure what hardware parameters this depends on, but using 8 as a constant may not fit everyone. Maybe better to default it to 1 (original behavior) and let people increase it via ENV if they want?

**Comment by manuelkasper** [comment]
> Maybe better to default it to 1 (original behavior) and let people increase it via ENV if they want?

Makes sense 😄👍

**Comment by rlanyi** [comment]
Thanks, updated

**Pull request merged**
